### ISSUE TITLE
Cannot read properties of undefined (reading 'getConfig')

### ISSUE THREAD

**Issue by maukoese** [batosai/adonis-attachment#2] opened 2024-09-02 09:32 UTC
Thank you so much for this package.

I have the latest version, and it's now throwing the  above error when I include the `@attachment()` decorator.

See image for details.

![Screenshot 2024-09-02 at 12 30 59](https://github.com/user-attachments/assets/9ea52fe9-cd63-4a43-8fc7-31c32d82ce1d)

**Comment by batosai** [comment] 2024-09-02 21:22
Hello @maukoese , I can't reproduce the issue.
Could you please provide more information? At what point during your application's execution does this occur?
What does your config/attachment.ts file look like?

**Comment by maukoese** [comment] 2024-10-06 21:34
Helo @batosai 

This is my config
![Screenshot 2024-10-07 at 00 31 41](https://github.com/user-attachments/assets/b8e47a00-665b-4b66-aadd-56edbde4bbee)

In a model like this, when I uncomment line 29, the above error occurs and the server dies. When I comment it out, the sever runs but now I can't upload any files.

![Screenshot 2024-10-07 at 00 32 31](https://github.com/user-attachments/assets/1f9adf28-8a09-4fdf-9fac-43350f6ad7b3)


I have a feeling it could be clashing with one or more of other installed packages, but I'm not sure. I want to set up a new project and see if I can reproduce, to isolate the issue.

**Comment by batosai** [comment] 2024-10-22 17:35
Hi, were you able to test? Can I see the package.json ?

**Comment by maukoese** [comment] 2024-10-22 19:24
I've setup other projects and the package works just fine.

I think it's a conflict with one of the other packages I'm using.

**Comment by batosai** [comment] 2024-10-22 20:46
Thanks for the feedback

**Comment by radudalbea** [comment] 2024-10-30 20:03
Hi guys,

I also have this issue.  @batosai what node version do you have? mine is v20.18.0 and I was able to reproduce it with minimum adonis setup.

**Comment by batosai** [comment] 2024-10-30 20:18
I am in 20.17.0, I will test as soon as possible with the higher versions. I would really like to repeat this problem.

**Comment by radudalbea** [comment] 2024-10-30 21:37
I found the issue. it's when you use it in a service provider. if you do something like:

import User from '#models/user';
this.app.container.singleton(UserRepository, async () => {
      return new UserRepository(User);
});

it will trigger the error from above. This is resolvable if you are using:

const User = () => import('#models/user');
this.app.container.singleton(UserRepository, async () => {
 const resolver = await User();
 const user = resolver.default;

 return new UserRepository(user);
});

So this part is covered. You do have a small bug with the Attachment toJSON method. it's a typo with the mimeType. in the code is mimetype. if you try to cache a model using the attachment it will trigger the error related to the required fields.

**Comment by batosai** [comment] 2024-10-30 23:41
How do you hide your model to cause this? Have you tried to directly modify the package in node-modules to check that this was the cause?

**Comment by radudalbea** [comment] 2024-10-31 00:05
If you are refering to the required fields error then yes. I modified your package and it works. It’s just a typo. Instead of serializing it with mimeType you are doing with mimetype. After this if I try to recreate another model with this data it will trigger the error.

**Comment by radudalbea** [comment] 2024-10-31 00:09
src/attachments/attachment.ts


toJSON(): Object {
    const data: any = {
      name: this.name,
      originalName: this.originalName,
      size: this.size,
      extname: this.extname,
      mimetype: this.mimeType,
      meta: this.meta,
    }

    if (this.variants) {
      this.variants!.map(async (v) => {
        data[v.key] = {
          name: v.name,
          extname: v.extname,
          mimetype: v.mimeType,
          meta: v.meta,
          size: v.size,
        }
      })
    }

**Comment by batosai** [comment] 2024-10-31 08:10
It's fix in 2.4.1

**Comment by filipebraida** [comment] 2024-11-06 15:44
Congratulations on the package!
I've run into the same issue. When I try to create a service with container.make, I get the same error. I tried it with version 2.4.1, but it didn’t work either. If I remove the field from the model, it works normally.

```error
   TypeError: Cannot read properties of undefined (reading 'getConfig')
 
   at _ts_decorate app/models/document.ts:3
   1|  import { DateTime } from 'luxon'
   2|  import { compose } from '@adonisjs/core/helpers'
 ❯ 3|  import { BaseModel, belongsTo, column, hasMany } from '@adonisjs/lucid/orm'
   4|  import { attachment, Attachmentable } from '@jrmc/adonis-attachment'
   5|  import type { Attachment } from '@jrmc/adonis-attachment/types/attachment'
   6|  import type { BelongsTo, HasMany } from '@adonisjs/lucid/types/relations'
   7|  
   8|  import Page from '#models/page'
 ```

```ts
@attachment({ preComputeUrl: true })
declare file: Attachment
```

**Comment by filipebraida** [comment] 2024-11-06 15:55
I've managed to isolate the issue. Now, with this version, `container.make` works. The main problem is that I'm using the `adonisjs-jobs` library, and it doesn't work within the Job. I think the library might not be instantiating something correctly.

**Comment by batosai** [comment] 2024-11-06 15:55
Hi @filipebraida, the radudalbea solution does not solve your need?
Do you have a public project or could I replicate that?

**Comment by filipebraida** [comment] 2024-11-06 15:56
thanks @batosai 
I'll create one to fully isolate the error and check if everything's working correctly.

**Comment by batosai** [comment] 2024-11-06 15:57
thanks @filipebraida 
I'm really taking a project with the error to work on a solution

**Comment by batosai** [comment] 2024-11-06 17:25
I will try to find a solution. 
In the meantime, as mentioned by radudalbea, you can rewrite your service like this:

```
export default class FileService {
  async test() {
    const Model = () => import('#models/file');
    const resolver = await Model();
    const File = resolver.default;

    const files = await File.all()
    console.log('testing')

    return files
  }
}
```

**Comment by filipebraida** [comment] 2024-11-06 19:45
Thanks @batosai 

Sorry, I misunderstood the thread. 
I ended up moving to another part of the development, but now I’m back to try the suggested solution.

**Comment by batosai** [comment] 2024-11-09 16:48
Hi,
it's fix in 2.4.2.

Thank you for your feedback.
To support the project, please star the repo, thank you.

**Closed** 2024-11-09 16:48 UTC

**Comment by filipebraida** [comment] 2024-11-09 17:19
Thank you for the help @batosai 
I ran a simple test here on the original project, and it worked.
The star has been there since launch :)

**Comment by maukoese** [comment] 2024-11-15 08:16
I'm still getting this error intermittently, it goes away when I remove the @attachment() decorator; but I have no clue what's causing it

**Comment by maukoese** [comment] 2024-11-15 08:18
> I am in 20.17.0, I will test as soon as possible with the higher versions. I would really like to repeat this problem.

Can I add to the repo I'm using so you see the setup?

**Comment by batosai** [comment] 2024-11-15 08:26
@maukoese, I want to come to see your project.

**Comment by maukoese** [comment] 2024-11-16 09:54
Hello @batosai, I have added you to the repo. KIndly confirm
